### ISSUE TITLE
GraphQL error: Topology was destroyed

### ISSUE THREAD

**Issue by tomitrescak** [apollostack/graphql-server#238] opened 2016-12-08 06:56 UTC
Hi, when the database connection breaks (i.e. I restart the database server), the app will never recuperate and I'm getting `GraphQL error: Topology was destroyed`.

The whole server needs to be restarted for this to start working again. Is this possible to tackle somehow? I'm a bit affraid now to put this into production as our DB server sits on a different machine. Thanks!

**Comment by stubailo** [comment] 2016-12-08 06:59
The word "Topology" doesn't appear anywhere in this repository, `graphql-tools`, or `graphql`, so this is probably some problem with your ORM or similar. Going to close this issue since there is no reproduction or evidence that the described outcome is a result of using GraphQL in any way.

**Closed by stubailo** 2016-12-08 06:59 UTC

**Comment by lorensr** [comment] 2018-07-22 04:01
Just ran into this! 😄 You can give options to Mongoose or `MongoClient.connect` that govern how hard it tries to reconnect to the db:

https://stackoverflow.com/questions/30909492/mongoerror-topology-was-destroyed

Default for Mongo node driver is 30 retries:

http://mongodb.github.io/node-mongodb-native/3.1/reference/connecting/connection-settings/

The below will retry all day long ☺️

```js
  const client = await MongoClient.connect(
    MONGO_URL,
    {
      reconnectTries: 86400
    }
  )
```
